name: push release image

on:
  push:
    tags:
      - '*.*.*'

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set output
        id: vars
        run: echo "DOCKER_IMAGE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - uses: docker/setup-buildx-action@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3.0.0
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/s6w2n1r6

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            public.ecr.aws/s6w2n1r6/aws-apigateway-exporter:${{ steps.vars.outputs.DOCKER_IMAGE_TAG }}
